Added files
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-michallibov pull request #3
Opened 2022-03-26 12:16 UTC by michallibov

Fixed the previous pull request (of the deleted files)

2022-03-26 13:28 UTC, talbarfm requested changes

2022-03-26 13:28 UTC, talbarfm commented on cup-of-join.py
> +    for x in lists:
Use list comprehension and zip to remove this forloop

2022-03-26 13:28 UTC, talbarfm commented on cup-of-join.py
> +        new_list.extend(x)      # adds the given list to the output list without []
Single line comments start with capital letter and on a separate line

2022-03-26 13:28 UTC, talbarfm commented on cup-of-join.py
> +        return None
https://stackoverflow.com/questions/1839289/why-should-functions-always-return-the-same-type

2022-03-26 13:28 UTC, talbarfm commented on piece-of-cake.py
> +"""
You dont need this documentation, the function documentation is enough

2022-03-26 13:28 UTC, talbarfm commented on piece-of-cake.py
> +    for ingredient in ingredients:
use functools.reduce to remove this for loop

2022-03-26 13:28 UTC, talbarfm commented on piece-of-cake.py
> +print(get_recipe_price({'chocolate': 18, 'milk': 8}, milk=100, chocolate=200))
Add newline at eof

2022-03-26 13:28 UTC, talbarfm commented on piece-of-cake.py
> +print(get_recipe_price({'chocolate': 18, 'milk': 8}, milk=100, chocolate=200))
surround this in name == main 
read this to understand  https://www.freecodecamp.org/news/if-name-main-python-example/

2022-03-26 13:28 UTC, talbarfm commented on cup-of-join.py
> +In this program I rewrote the known function 'join' for lists. This function gets
you don't need this description

2022-03-27 21:01 UTC, michallibov commented on cup-of-join.py
> +    for x in lists:
I was trying to figure out how to do that in a better way than how I did but couldn't find a way to get rid of the parenthesis inside the list. I also didn't find a way to not use the pop function after the list comprehension. I know it's not perfect..

2022-03-28 19:06 UTC, michallibov commented on cup-of-join.py
> +    for x in lists:
I managed to succeed doing it and now it works fine:P

2022-03-30 08:27 UTC, lovodkin93 approved these changes
well done!

2022-03-30 08:27 UTC, merged

2022-04-03 15:31 UTC, itayday commented on piece-of-cake.py
> +    total_price = functools.reduce(lambda price, ingredient: price + ingredients.get(ingredient) *
Great!